name: 'Build'
on:
  schedule:
    #  every monday
    - cron: '0 0 * * 1'
  push:
  workflow_dispatch:
jobs:
  push:
    strategy:
      matrix:
        variant: [tier1, tier2, tier3]
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            alphanecron/judge-env
          tags: |
            type=raw,${{ matrix.variant }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          target: ${{ matrix.variant }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
